### ISSUE TITLE
Pls help  me, where is utils.py? i can't dowloads it.

### ISSUE THREAD

**Issue by phanthuthao** [scott-robbins/Snoopy#1]
Pls help  me, where is utils.py? i can't dowloads it.

**Comment by scott-robbins** [comment]
Sorry it took me so long to see the issue you posted. I didn't even realize anyone else was using this code! 
Yeah I'm bad at keeping scripts in organized modules, and utils.py floats around. It's duplicated in a few places (I think [/code/R3D/utils.py](https://raw.githubusercontent.com/scott-robbins/Snoopy/master/code/R3D/utils.py) is one). Much of this project is not being uploaded to github, so there might things missing. Let me know if this happens again and I'll be much more responsive.
